# Generated by Django 4.1.13 on 2024-05-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=155)),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'mail_template',
            },
        ),
    ]
