# Generated by Django 4.1.13 on 2024-05-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='subject',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
