# Generated by Django 5.0.3 on 2024-05-04 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_course_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='material',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='material',
            name='software',
        ),
        migrations.RemoveField(
            model_name='material',
            name='textbook',
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='outline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.subjectoutline'),
        ),
        migrations.AddField(
            model_name='material',
            name='type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
