# Generated by Django 5.0.3 on 2024-05-04 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_learningoutcome_evaluation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='outline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.subjectoutline'),
        ),
    ]
