# Generated by Django 5.0.3 on 2024-05-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_learningoutcome_no_alter_learningoutcome_objective'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningoutcome',
            name='no',
        ),
        migrations.AddField(
            model_name='material',
            name='no',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
