# Generated by Django 5.0.3 on 2024-05-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_learningoutcome_no_material_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='co_courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='co_courses', to='core.course'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='preceding_courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='preceding_courses', to='core.course'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, null=True, related_name='prerequisites', to='core.course'),
        ),
    ]
