# Generated by Django 4.1.13 on 2024-05-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_course_code_alter_instructor_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='subjectoutline',
            name='year',
            field=models.ManyToManyField(related_name='subject_outlines', to='core.schoolyear'),
        ),
    ]
