# Generated by Django 4.1.13 on 2024-06-13 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_evaluation_method_alter_objective_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectoutline',
            name='years',
        ),
        migrations.AddField(
            model_name='subjectoutline',
            name='years',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_outlines', to='core.schoolyear'),
        ),
    ]
