# Generated by Django 4.1.13 on 2024-06-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_subjectoutline_years_subjectoutline_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolyear',
            name='year',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
