# Generated by Django 4.1.13 on 2024-06-13 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_schoolyear_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectoutline',
            name='instructor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_outline', to='core.instructor'),
        ),
    ]
