# Generated by Django 4.1.13 on 2024-06-13 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_subjectoutline_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectoutline',
            name='years',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_outlines', to='core.schoolyear'),
        ),
    ]
