# Generated by Django 4.1.13 on 2024-06-13 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_subjectoutline_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectoutline',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_outline', to='core.instructor'),
        ),
    ]
